name: NexoScreens
version: '${version}'
api-version: 1.21
author: mrjimin

main: com.github.mrjimin.nexoscreens.NexoScreens
loader: com.github.mrjimin.nexoscreens.NexoScreensLoader

dependencies:
  server:
    Nexo:
      load: BEFORE
      required: true
    ProtocolLib:
      load: BEFORE
      required: true
      join-classpath: true